{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafkahq.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "kafkahq.name" . }}
    helm.sh/chart: {{ include "kafkahq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  application-secrets.yml: {{.Values.secrets| b64enc | quote }}
{{- end }}