micronaut:
  application:
    name: kafkahq
  io:
    watch:
      paths: src/main
      restart: true
  router:
    static-resources:
      static:
        paths: classpath:static
        mapping: "${kafkahq.server.base-path:}/static/**"

jackson:
  module-scan: false

kafkahq:
  server:
    base-path: ""
  clients-defaults:
    consumer:
      properties:
        max.poll.records: 50
        isolation.level: read_committed
        group.id: KafkaHQ
        enable.auto.commit: "false"
